# Module 2: Programming Challenges
This notebook presents a series of programming exercises covering object-oriented programming, file input/output, exception handling, and NumPy operations. Each problem includes a description, input/output examples, a workspace for your solution, and a reference solution for comparison.

## Problem 1: Student Class
Write a program that defines a `Student` class with the following attributes: `name` (str), `age` (int), and `gpa` (float). The `__init__` method should initialize all three attributes. Add a method `is_honors()` that returns `True` if the student's GPA is greater than or equal to 3.5 and `False` otherwise.

Example:
```
s1 = Student("Alice", 20, 3.8)
print(s1.is_honors())  # True

s2 = Student("Bob", 22, 3.2)
print(s2.is_honors())  # False
```

In [1]:
# Write your solution here


In [2]:
# SOLUTION
class Student:
    def __init__(self, name, age, gpa):
        self.name = name
        self.age = age
        self.gpa = gpa

    def is_honors(self):
        return self.gpa >= 3.5

# Test
s1 = Student("Alice", 20, 3.8)
s2 = Student("Bob", 22, 3.2)
print(s1.is_honors())  # True
print(s2.is_honors())  # False

True
False


## Problem 2: BankAccount Class
Create a `BankAccount` class with a private attribute `__balance` initialized to 0. Provide three methods:
- `deposit(amount)`: adds `amount` to the balance if `amount` is positive.
- `withdraw(amount)`: subtracts `amount` from the balance if sufficient funds exist; otherwise, prints an error message.
- `get_balance()`: returns the current balance.

Example:
```
acc = BankAccount()
acc.deposit(100)
acc.withdraw(30)
print(acc.get_balance())   # 70
acc.withdraw(100)          # prints: Insufficient funds.
```

In [3]:
# Write your solution here


In [4]:
# SOLUTION
class BankAccount:
    def __init__(self):
        self.__balance = 0

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount

    def withdraw(self, amount):
        if amount <= self.__balance:
            self.__balance -= amount
        else:
            print("Insufficient funds.")

    def get_balance(self):
        return self.__balance

# Test
acc = BankAccount()
acc.deposit(100)
acc.withdraw(30)
print(acc.get_balance())   # 70
acc.withdraw(100)          # Insufficient funds.

70
Insufficient funds.


## Problem 3: GradStudent (Inheritance)
Define a `GradStudent` class that inherits from `Student` (from Problem 1). It should accept an additional parameter `thesis_topic` (str) in the constructor and pass `name`, `age`, and `gpa` to the parent class. Add a method `research()` that returns a string of the form `"<name> is researching <thesis_topic>."`.

Example:
```
gs = GradStudent("Charlie", 25, 3.9, "Quantum Computing")
print(gs.is_honors())   # True (inherited)
print(gs.research())    # Charlie is researching Quantum Computing.
```

In [5]:
# Write your solution here


In [6]:
# SOLUTION
class Student:
    def __init__(self, name, age, gpa):
        self.name = name
        self.age = age
        self.gpa = gpa

    def is_honors(self):
        return self.gpa >= 3.5


class GradStudent(Student):
    def __init__(self, name, age, gpa, thesis_topic):
        super().__init__(name, age, gpa)
        self.thesis_topic = thesis_topic

    def research(self):
        return f"{self.name} is researching {self.thesis_topic}."

# Test
gs = GradStudent("Charlie", 25, 3.9, "Quantum Computing")
print(gs.is_honors())   # True
print(gs.research())    # Charlie is researching Quantum Computing.

True
Charlie is researching Quantum Computing.


## Problem 4: File Analysis
Write a program that reads a text file and counts the number of lines, words, and characters (including whitespace) in the file. Print the results in the format: `"Lines: <N>, Words: <M>, Characters: <C>"`.

Assume the file `sample.txt` exists with the following content:
```
Hello world
Python is fun
```
Expected output: `Lines: 2, Words: 5, Characters: 27`

In [7]:
# Write your solution here


In [8]:
# SOLUTION
# Create sample file first
with open("sample.txt", "w") as f:
    f.write("Hello world\nPython is fun")

with open("sample.txt", "r") as f:
    content = f.read()

lines = content.splitlines()
num_lines = len(lines)
num_words = len(content.split())
num_chars = len(content)

print(f"Lines: {num_lines}, Words: {num_words}, Characters: {num_chars}")

Lines: 2, Words: 5, Characters: 25


## Problem 5: Number File Sum
Write a program that performs two tasks:
1. Write a list of numbers `[10, 20, 30, 40, 50]` to a file named `numbers.txt`, one number per line.
2. Read the numbers back from the file, convert each line to an integer, and compute (and print) their sum.

Expected output: `Sum: 150`

In [9]:
# Write your solution here


In [10]:
# SOLUTION
numbers = [10, 20, 30, 40, 50]

# Write to file
with open("numbers.txt", "w") as f:
    for num in numbers:
        f.write(str(num) + "\n")

# Read back and sum
total = 0
with open("numbers.txt", "r") as f:
    for line in f:
        total += int(line.strip())

print(f"Sum: {total}")

Sum: 150


## Problem 6: Safe Division
Write a function `safe_divide(a, b)` that returns the result of `a / b`. Use exception handling to catch `ZeroDivisionError` and `TypeError`. In each case, print an appropriate error message and return `None`.

Example:
```
print(safe_divide(10, 2))   # 5.0
print(safe_divide(10, 0))   # Error: Cannot divide by zero. (returns None)
print(safe_divide(10, "2")) # Error: Both arguments must be numbers. (returns None)
```

In [11]:
# Write your solution here


In [12]:
# SOLUTION
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")
        return None
    except TypeError:
        print("Error: Both arguments must be numbers.")
        return None

# Test
print(safe_divide(10, 2))   # 5.0
print(safe_divide(10, 0))   # Error message and None
print(safe_divide(10, "2")) # Error message and None

5.0
Error: Cannot divide by zero.
None
Error: Both arguments must be numbers.
None


## Problem 7: NumPy Random Matrix
Using NumPy, create a 5x5 matrix of random integers in the range 1 to 100 (inclusive). Print the matrix. Then find and print the maximum value, the minimum value, and their respective row and column positions.

Example output:
```
Maximum: 99 at position (row=3, col=1)
Minimum: 2 at position (row=0, col=4)
```

In [13]:
# Write your solution here


In [14]:
# SOLUTION
import numpy as np

np.random.seed(42)  # For reproducibility
matrix = np.random.randint(1, 101, size=(5, 5))
print("Matrix:\n", matrix)

max_val = matrix.max()
max_pos = np.unravel_index(matrix.argmax(), matrix.shape)
min_val = matrix.min()
min_pos = np.unravel_index(matrix.argmin(), matrix.shape)

print(f"Maximum: {max_val} at position (row={max_pos[0]}, col={max_pos[1]})")
print(f"Minimum: {min_val} at position (row={min_pos[0]}, col={min_pos[1]})")

Matrix:
 [[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]]
Maximum: 100 at position (row=2, col=1)
Minimum: 2 at position (row=3, col=1)


## Problem 8: NumPy Array Operations
Create two NumPy arrays `a` and `b` where `a` is `[1, 2, 3]` and `b` is `[4, 5, 6]`. Compute and print:
1. Element-wise multiplication (the product of corresponding elements).
2. The dot product (scalar result of matrix multiplication for 1-D arrays).

Expected output:
```
Element-wise product: [ 4 10 18]
Dot product: 32
```

In [15]:
# Write your solution here


In [16]:
# SOLUTION
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

element_wise = a * b
dot_product = np.dot(a, b)

print("Element-wise product:", element_wise)
print("Dot product:", dot_product)

Element-wise product: [ 4 10 18]
Dot product: 32


## Problem 9: Boolean Indexing on Exam Scores
Given a NumPy array of exam scores, use boolean indexing to select and print only the passing scores (scores greater than or equal to 60). Also print the number of passing students and the number of failing students.

Use the following scores:
```python
scores = np.array([45, 78, 92, 33, 60, 55, 88, 71, 49, 95])
```

Expected output:
```
Passing scores: [78 92 60 88 71 95]
Passing: 6, Failing: 4
```

In [17]:
# Write your solution here


In [18]:
# SOLUTION
import numpy as np

scores = np.array([45, 78, 92, 33, 60, 55, 88, 71, 49, 95])

passing = scores[scores >= 60]
num_passing = len(passing)
num_failing = len(scores) - num_passing

print("Passing scores:", passing)
print(f"Passing: {num_passing}, Failing: {num_failing}")

Passing scores: [78 92 60 88 71 95]
Passing: 6, Failing: 4


## Problem 10: File-to-NumPy Statistics
Read the file `numbers.txt` created in Problem 5 into a NumPy array. Compute and print the mean and standard deviation of the numbers.

Expected output:
```
Mean: 30.0
Standard deviation: 14.142135623730951
```

In [19]:
# Write your solution here


In [20]:
# SOLUTION
import numpy as np

data = np.loadtxt("numbers.txt")
mean_val = np.mean(data)
std_val = np.std(data)

print(f"Mean: {mean_val}")
print(f"Standard deviation: {std_val}")

Mean: 30.0
Standard deviation: 14.142135623730951
