# Module 2: Object-Oriented Programming, File I/O, and NumPy
This module covers class definitions, inheritance, special methods, file input/output, exception handling, and essential NumPy operations for numerical computing. Each section includes a runnable demonstration.

## 1. Classes and Objects
A class is a blueprint for constructing objects that bundle data (attributes) with behavior (methods). The constructor `__init__` receives the instance as its first parameter, conventionally named `self`, and initializes instance attributes. Instance methods access and modify these attributes through the `self` reference.

In [43]:
class Book:
    def __init__(self, title, author, pages):
        self.title = title
        self.author = author
        self.pages = pages

    def summary(self):
        return f"'{self.title}' by {self.author} ({self.pages} pp.)"

    def is_long(self):
        return self.pages > 300

b1 = Book("1984", "Orwell", 328)
b2 = Book("The Stranger", "Camus", 123)
print(b1.summary())
print(f"Long: b1={b1.is_long()}, b2={b2.is_long()}")

'1984' by Orwell (328 pp.)
Long: b1=True, b2=False


### Class Attributes vs Instance Attributes

**Instance attributes** (created with `self.attr` inside `__init__`) belong to each individual object.

**Class attributes** are defined directly inside the class body (not in `__init__`) and are **shared across all instances**. Modifying a class attribute through the class name affects all instances, but assigning to it through an instance creates a new instance attribute instead.

In [46]:
class Student:
    school = 'AI Academy'  # class attribute — shared by all students

    def __init__(self, name):
        self.name = name   # instance attribute — unique to each student

s1 = Student('Alice')
s2 = Student('Bob')
print(s1.school, s1.name)   # AI Academy Alice
print(s2.school, s2.name)   # AI Academy Bob

# Changing the class attribute affects all instances
Student.school = 'Data Science Institute'
print(s1.school)            # Data Science Institute
print(s2.school)            # Data Science Institute

# Assigning through an instance creates an instance attribute
s1.school = 'Local Campus'
print(s1.school)            # Local Campus (now an instance attribute)
print(s2.school)            # Data Science Institute (still class attribute)

AI Academy Alice
AI Academy Bob
Data Science Institute
Data Science Institute
Local Campus
Data Science Institute


## 2. Inheritance
Inheritance permits a child class to reuse and extend the functionality of a parent class. The built-in function `super()` invokes the parent constructor or method, eliminating redundant code. Method overriding allows the child to supply its own implementation of an inherited method while retaining the option to delegate to the parent implementation.

In [49]:
class EBook(Book):
    def __init__(self, title, author, pages, file_format):
        super().__init__(title, author, pages)
        self.file_format = file_format

    def summary(self):
        return super().summary() + f" [{self.file_format}]"

eb = EBook("Dune", "Herbert", 412, "EPUB")
print(eb.summary())

'Dune' by Herbert (412 pp.) [EPUB]


## 3. Special Methods
Special methods (dunder methods) define how objects interact with Python's built-in operators and functions. `__str__` returns a human-readable string invoked by `print()`; `__repr__` returns an unambiguous representation for debugging; and `__len__` enables the `len()` built-in on user-defined objects.

In [52]:
class Vector2D:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        return f"Vector({self.x}, {self.y})"

    def __repr__(self):
        return f"Vector2D({self.x}, {self.y})"

    def __len__(self):
        return 2

v = Vector2D(3, 4)
print(str(v))
print(repr(v))
print(len(v))

Vector(3, 4)
Vector2D(3, 4)
2


## 4. File I/O
The built-in `open()` function returns a file object for reading or writing text. The `with` statement acts as a context manager and guarantees the file is closed after the block executes, even when exceptions occur. Common modes include `'r'` (read), `'w'` (write, overwriting existing content), `'a'` (append), and `'r+'` (read/write). The `readlines()` method returns all remaining lines as a list.

In [55]:
# Write sample records to a file, then read them back line by line.
records = ["1984,Orwell,328\n", "Dune,Herbert,412\n", "Sapiens,Harari,464\n"]

with open("books.txt", "w") as f:
    f.writelines(records)

with open("books.txt", "r") as f:
    for line in f.readlines():
        print(line.strip())

1984,Orwell,328
Dune,Herbert,412
Sapiens,Harari,464


## 5. Exception Handling
Exception handling uses `try`/`except` blocks to intercept runtime errors and prevent abrupt program termination. The `else` clause executes only when no exception is raised, and `finally` always runs regardless of success or failure. Common built-in exception types include `ValueError`, `TypeError`, `FileNotFoundError`, and `ZeroDivisionError`.

In [58]:
def safe_parse_int(value):
    try:
        result = int(value)
    except ValueError:
        return f"'{value}' is not a valid integer."
    except TypeError:
        return "Input must be a string or number."
    else:
        return f"Parsed value: {result}"
    finally:
        print("  [parse attempt completed]")

print(safe_parse_int("42"))
print(safe_parse_int("abc"))
print(safe_parse_int(None))

  [parse attempt completed]
Parsed value: 42
  [parse attempt completed]
'abc' is not a valid integer.
  [parse attempt completed]
Input must be a string or number.


In [60]:
# Read a file safely using try/except and with statement
def read_file_safe(filename):
    try:
        with open(filename, 'r') as f:
            content = f.read()
        return content
    except FileNotFoundError:
        print(f'Error: File {filename} not found.')
        return None
    except PermissionError:
        print(f'Error: Permission denied for {filename}.')
        return None

# Test with a non-existent file
result = read_file_safe('nonexistent.txt')
print(result)  # None


Error: File nonexistent.txt not found.
None


## 6. Introduction to NumPy
NumPy is the foundational library for numerical computing in Python. Its core data structure, the `ndarray`, stores homogeneous data in contiguous memory, enabling vectorized operations that are orders of magnitude faster than equivalent Python list loops. The conventional import alias is `import numpy as np`.

In [61]:
import numpy as np

py_list = [1, 2, 3, 4]
np_arr = np.array(py_list)

print("List * 2:", py_list * 2)      # list repetition
print("Array * 2:", np_arr * 2)      # element-wise multiplication
print("Array + 10:", np_arr + 10)    # broadcasting scalar addition

List * 2: [1, 2, 3, 4, 1, 2, 3, 4]
Array * 2: [2 4 6 8]
Array + 10: [11 12 13 14]


## 7. Creating Arrays
NumPy provides multiple factory functions for array construction. `np.array()` converts Python sequences; `np.zeros()` and `np.ones()` create arrays filled with a constant; `np.arange()` generates ranges with a step; `np.linspace()` produces evenly spaced values; `np.eye()` creates an identity matrix; and `np.random` generates arrays of pseudo-random values from various distributions.

In [64]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.zeros((2, 3))
a3 = np.ones(4)
a4 = np.arange(0, 10, 2)
a5 = np.linspace(0, 1, 5)
a6 = np.eye(3)
a7 = np.random.rand(2, 2)

print("Zeros:\n", a2)
print("Linspace:", a5)
print("Identity:\n", a6)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 8. Array Properties
Every NumPy array exposes attributes that describe its structure and data type. `shape` is a tuple of dimension sizes, `ndim` reports the number of axes, `size` gives the total element count, and `dtype` identifies the type of stored values (`float64`, `int32`, etc.). These attributes are read-only and reflect the array's current state.

In [67]:
features = np.array([[1.2, 3.4, 0.5],
                     [2.1, 1.1, 4.0],
                     [0.9, 2.2, 3.1]])

print("Shape:", features.shape)
print("Dimensions:", features.ndim)
print("Total elements:", features.size)
print("Data type:", features.dtype)

Shape: (3, 3)
Dimensions: 2
Total elements: 9
Data type: float64


### 1D Array Slicing and the View vs Copy Warning

One-dimensional NumPy arrays slice exactly like Python lists using `[start:stop:step]`. You can reverse an array with `[::-1]`.

**Critical distinction**: NumPy slices return a **view** (a window into the original array), not an independent copy. Modifying a view also modifies the original array. Use `.copy()` when you need an independent array.

In [70]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# 1D slicing works like Python lists
print(arr[1:4])      # [20 30 40]
print(arr[::2])      # [10 30 50] (every second element)
print(arr[::-1])     # [60 50 40 30 20 10] (reversed)

# CRITICAL: slices are VIEWS, not copies
slice_view = arr[1:4]
slice_view[0] = 999
print('Modified slice:', slice_view)
print('Original array:', arr)  # Original is also changed!

# Use .copy() when you need an independent array
arr2 = np.array([10, 20, 30, 40, 50, 60])
slice_copy = arr2[1:4].copy()
slice_copy[0] = 999
print('Modified copy:', slice_copy)
print('Original array:', arr2)  # Original is unchanged

[20 30 40]
[10 30 50]
[60 50 40 30 20 10]
Modified slice: [999  30  40]
Original array: [ 10 999  30  40  50  60]
Modified copy: [999  30  40]
Original array: [10 20 30 40 50 60]


## 9. Indexing, Slicing, and Boolean Indexing
NumPy arrays support multi-dimensional indexing with comma-separated indices: `arr[row, column]`. Slices use the `start:stop:step` pattern for each axis. Boolean indexing selects elements that satisfy a logical condition by passing a boolean array of the same shape as the index. The function `np.where()` returns indices matching a condition or performs element-wise conditional selection.

In [73]:
m = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 11, 12, 13]])

print("Element [1,2]:", m[1, 2])
print("First row:", m[0])
print("Second column:", m[:, 1])
print("Top-left 2x2:\n", m[:2, :2])

# Boolean indexing
mask = m > 40
print("Values > 40:", m[mask])

# np.where
labels = np.where(m > 40, "HIGH", "LOW")
print("Labels:\n", labels)

Element [1,2]: 70
First row: [10 20 30 40]
Second column: [20 60 11]
Top-left 2x2:
 [[10 20]
 [50 60]]
Values > 40: [50 60 70 80 90]
Labels:
 [['LOW' 'LOW' 'LOW' 'LOW']
 ['HIGH' 'HIGH' 'HIGH' 'HIGH']
 ['HIGH' 'LOW' 'LOW' 'LOW']]


## 10. Array Operations and Broadcasting
Arithmetic operators on NumPy arrays apply element-wise: `+`, `-`, `*`, `/`, `**` all operate per-element. Matrix multiplication uses the `@` operator or `np.dot()`. Broadcasting automatically expands the smaller array along mismatched dimensions when their shapes are compatible: dimensions are aligned from the right, and each must either match or be equal to 1.

In [76]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b:", a + b)
print("a * b:", a * b)
print("a ** 2:", a ** 2)

# Matrix multiplication
W = np.array([[1, 2], [3, 4]])
x = np.array([5, 6])
print("W @ x:", W @ x)

# Broadcasting
A = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([10, 20, 30])
print("A + v:\n", A + v)

a + b: [5 7 9]
a * b: [ 4 10 18]
a ** 2: [1 4 9]
W @ x: [17 39]
A + v:
 [[11 22 33]
 [14 25 36]]


## 11. Useful NumPy Functions
NumPy provides a comprehensive set of reduction and transformation functions. `sum`, `mean`, `std`, `max`, and `min` compute aggregate statistics; `argmax` and `argmin` return the indices of the extremum; and `reshape` rearranges element layout without copying data. The `axis` parameter controls the dimension along which reductions are applied (`axis=0` for column-wise, `axis=1` for row-wise).

In [79]:
scores = np.array([[85, 92, 78],
                   [90, 88, 95],
                   [70, 75, 72]])

print("Sum per row:", np.sum(scores, axis=1))
print("Mean per column:", np.mean(scores, axis=0))
print("Max overall:", np.max(scores))
print("Min overall:", np.min(scores))
print("Std of all scores: {:.2f}".format(np.std(scores)))
print("Best test index for student 0:", np.argmax(scores[0]))

# Reshape
flat = scores.reshape(-1)
print("Flattened:", flat)

Sum per row: [255 273 217]
Mean per column: [81.66666667 85.         81.66666667]
Max overall: 95
Min overall: 70
Std of all scores: 8.70
Best test index for student 0: 1
Flattened: [85 92 78 90 88 95 70 75 72]


## 12. Practical Example
The following example combines array creation, element-wise operations, boolean indexing, and statistical functions in a realistic data processing workflow. Simulated sensor readings from three devices over four time steps are analyzed to detect anomalies and compute per-device summaries.

In [82]:
# Simulated sensor data: 3 devices, 4 readings each
readings = np.array([[22.1, 23.0, 21.8, 45.7],
                     [19.5, 19.8, 20.1, 19.9],
                     [25.0, 24.8, 25.3, 24.9]])

# Center data by subtracting per-device means (broadcasting)
centered = readings - readings.mean(axis=1, keepdims=True)

# Flag anomalies: absolute deviation exceeding 5.0
anomalies = np.abs(centered) > 5.0
print("Anomaly mask:\n", anomalies)
print("Anomalous values:", readings[anomalies])

# Per-device statistics
print("\nDevice means:", readings.mean(axis=1))
print("Device standard deviations:", readings.std(axis=1))

Anomaly mask:
 [[ True  True  True  True]
 [False False False False]
 [False False False False]]
Anomalous values: [22.1 23.  21.8 45.7]

Device means: [28.15  19.825 25.   ]
Device standard deviations: [10.14211516  0.21650635  0.18708287]


## Summary
This module covered Python's object-oriented programming model (classes, inheritance, and special methods), file input/output with context managers, structured exception handling with `try`/`except`/`else`/`finally`, and the NumPy library for efficient numerical computing including array creation, slicing, broadcasting, and statistical reductions. These techniques serve as the foundation for data analysis and scientific computing in subsequent modules.