# Module 4: NumPy Tutorial

**numpy:** is strong data structure for deal with arrays or matrix in python, contains alot of useful function.
it is outside(built out) library, so fast more from built in moduls list & set & tuple & dict in python.

you can install by terminal or powershell or command line(cmd) like:
`PS C:\Users\mmsba> pip install numpy`

**(notes: 1-must first install python for use `pip`,2-`cmd` and `powershell` is defualt in windows just search)
**
to varity from libraries installition:
`PS C:\Users\mmsba> pip list`

to varity from python if exist:
`PS C:\Users\mmsba> python "or" py`

to uninstall outside library:
`PS C:\Users\mmsba>pip uninstall library_name`


In [382]:
# Important 1-first to use numpy must import it 2-second must run the part contains `import numpy as np` always

import numpy as np  ## np is shorcuts for numpy library

In [383]:
array1 = np.array([1, 2, 3])  # like defualt == np.array([1,2,3],dtype=int)
array2 = np.array([1, 2, 3.0])  # becuase (3.) defualt == np.array([1,2,3],dtype=float)
print(array1)
print(array2)
print(array1 == array2)

[1 2 3]
[1. 2. 3.]
[ True  True  True]


In [384]:
array1  # always in markdown code with file.ipynb extention os last variable can print to alone it.

array([1, 2, 3])

In [385]:
array2 = np.array([1, 2, "3"])  # like defualt == np.array([1,2,3],dtype=str)
print(array1)
print(array2)
array1 == array2

[1 2 3]
['1' '2' '3']


array([False, False, False])

In [386]:
# wrong syntax for 2d, array = np.array([1,2,3],[4,5,6])
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [387]:
array1 = np.array([1, 2, 3.5])
print(array1)
array2 = np.array([1, 2, 3], dtype=str)
print(array2)

array1 == array2

[1.  2.  3.5]
['1' '2' '3']


array([False, False, False])

## python data type

**notes** about data types in python `int,float,str, complex ds=list,tuple,set,dict,map,...` only not contains long or double or sign or unsign number or char for charecters
String is `str` in python like:


In [388]:
# str_var="Hello"+' or one qution'+''' for multi line'''+1+22   #can only concatenate str (not "int") to str
str_var = (
    'double one qution " ' + " or one qution ' " + """ for multi line """ + "1" + "22"
)
print(str_var)  # wrong str="" str is reserved word
print(type(str_var))

double one qution "  or one qution '  for multi line 122
<class 'str'>


In [389]:
myname = "mohammed"
print("my name is", myname)  # important defualt attribute sep=" ",end="\n"
print("my name is", myname, sep="")
print("my name is", myname, sep="#")


print("my name is", myname, sep=" ", end=" $$ ")
print("my name is", myname, sep="#")

my name is mohammed
my name ismohammed
my name is#mohammed
my name is mohammed $$ my name is#mohammed


In [390]:
myname = "mohammed"
age = 24
print(f"my name is {myname} my age is {age}")  # bestest
print("my name is {} my age is {}".format(myname, age))
print("my name is {0:} my age is {1:}".format(myname, age))  # index
print("my name is {1:} my age is {0:}".format(age, myname))  # index

# python it is so easy belive me because easy to read & understand

my name is mohammed my age is 24
my name is mohammed my age is 24
my name is mohammed my age is 24
my name is mohammed my age is 24


In [441]:
list_var = [1, 2, 3, 4, 5]  # wrong list=[] is reserved word
print(list_var)
print(type(list_var))
arrnp = np.array(list_var)
print(arrnp)
print(type(arrnp))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [446]:
set_var = {1, 2, 3, 4, 6}  # wrong set={} is reserved word
print(set_var)
print(type(set_var))
arrnp = np.array(set_var)
print(arrnp)
print(type(arrnp))

{1, 2, 3, 4, 6}
<class 'set'>
{1, 2, 3, 4, 6}
<class 'numpy.ndarray'>


## Numpy functions


In [393]:
arr = np.arange(5)  # default start=0,end=5,step=1
arr

array([0, 1, 2, 3, 4])

In [394]:
arr = np.arange(0, 5)  # default step=1 remember
arr

array([0, 1, 2, 3, 4])

In [395]:
arr = np.arange(0, 11, 2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [396]:
np.arange(0, 100, 11)

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [397]:
np.arange(100, 0, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [398]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [399]:
arr = np.linspace(0, 1, 9)  # important number
arr

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [400]:
arr = np.linspace(0, 1, 10)  # defualt float
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [401]:
arr = np.linspace(1, 5, 13, dtype=int)  # force casting int
arr

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5])

In [448]:
arr = np.linspace(1, 5, 13).astype(int)  # force casting int
arr

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5])

In [452]:
arr = np.linspace(10, 9, 9)-9 # force casting int
arr

array([1.   , 0.875, 0.75 , 0.625, 0.5  , 0.375, 0.25 , 0.125, 0.   ])

In [403]:
import random  # review random number library built in python

print(random.randint(1, 10))  # 10 not include in python
print(random.randint(1, 10))  # random number
print(random.randint(1, 10))  # random number
print(
    "random.random(): ", random.random()
)  # very important random btw float(0-1) # 1 not include
print(random.random() * 10)  # btw float(1-10) # 10 not include like 0.1*10=1.000
print(int(25 + random.random() * 10))  # btw int(25-35) # 10 not include

7
8
5
random.random():  0.5930327767414846
9.407516499381668
34


In [404]:
print(np.random.randint(10))  # not array  output one random number
print(np.random.randint(20, 50))
# random int array by numpy
arr = np.random.randint(20, 50, 10)  # btw int(20-50) count=10
arr

6
26


array([43, 21, 38, 36, 26, 39, 28, 44, 32, 25], dtype=int32)

In [405]:
np.random.randint(10)  # not print it becuase not last line
np.random.randint(20, 50)  # not print it becuase not last line

np.random.randint(1, 11, 4)  #  btw int(1-11) count=4

array([4, 2, 5, 5], dtype=int32)

In [406]:
print(np.random.randint(0, 1, 5))  #  btw int(0-1) count=5
print(np.random.randint(0, 10, 5))  #  btw int(0-10) count=5

[0 0 0 0 0]
[2 8 0 8 7]


In [407]:
print(np.random.random(10))
print(np.random.random(10) * 5)
# print(int(np.random.random(10)*10)) #only length-1 arrays can be converted to Python scalars
print(list(map(int, np.random.random(5) * 10)))  #  btw int(1-10) count=5

[0.92283552 0.96265914 0.55059718 0.39379906 0.73221727 0.63285924
 0.23436092 0.28084918 0.95078394 0.64307051]
[2.55274366 4.51849116 4.13036387 1.92880167 4.84410267 0.07594661
 2.77436039 0.75338118 4.28953574 0.40126704]
[3, 9, 9, 5, 4]


In [408]:
arr = np.zeros(4)  # defualt float
print(arr)
print("type(arr):       ", type(arr))
print("type(arr.dtype): ", type(arr.dtype))
print("arr.dtype:       ", arr.dtype)

[0. 0. 0. 0.]
type(arr):        <class 'numpy.ndarray'>
type(arr.dtype):  <class 'numpy.dtypes.Float64DType'>
arr.dtype:        float64


In [409]:
arr = np.zeros((2, 2), dtype=int)
print(arr)

[[0 0]
 [0 0]]


In [410]:
arr = np.zeros((2, 1, 3))  # narr=2,rows=1,columns=3
print(arr)

[[[0. 0. 0.]]

 [[0. 0. 0.]]]


In [411]:
ones_float = np.ones((2, 2, 3))
print(ones_float)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [412]:
ones_int = np.ones((4, 2), dtype=int)  # rows=4,columns=2
ones_int

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [413]:
print(type(ones_float))

print(ones_float.dtype)
print(ones_int.dtype)
print(ones_float.dtype.name)  # name feild in class dtype
print(ones_int.dtype.name)

<class 'numpy.ndarray'>
float64
int64
float64
int64


In [414]:
ones_int = ones_float.astype(int) 
#astype convert return copy not change address original value
print(ones_int)
print(ones_int.dtype)
ones_str = ones_float.astype(str)
print(ones_float)
print(ones_float.dtype)
print(ones_str)
print(ones_str.dtype)
# ones_str.astype(int)# 1.0 not base 10 to convert int from str
ones_str.astype(float)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int64
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
float64
[[['1.0' '1.0' '1.0']
  ['1.0' '1.0' '1.0']]

 [['1.0' '1.0' '1.0']
  ['1.0' '1.0' '1.0']]]
<U32


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [415]:
arr=np.arange(11,100,11)
print(arr)
print("len: ",len(arr))
print("shape: ",arr.shape)
print("size: ",arr.size)
print("ndim: ",arr.ndim)

[11 22 33 44 55 66 77 88 99]
len:  9
shape:  (9,)
size:  9
ndim:  1


In [416]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("len: ",len(arr)) #len for np arr but size for all element
print("shape: ",arr.shape)
print("size: ",arr.size)
print("ndim: ",arr.ndim)

[[1 2 3]
 [4 5 6]]
len:  2
shape:  (2, 3)
size:  6
ndim:  2


In [417]:
arr=np.ones((3,4))#wrong syntax np.ones(3,4) Cannot interpret '4' as a data type
print(arr)
print("len: ",len(arr))
print("shape: ",arr.shape)
print("size: ",arr.size)
print("ndim: ",arr.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
len:  3
shape:  (3, 4)
size:  12
ndim:  2


In [418]:
a=np.array([1,11,111])
b=np.array([2,22,222])
c=np.array([[6,2,3],[4,5,6]])
print(np.append(a,c))
print(np.append(c,a))
# print(np.append(c,a,b))

[  1  11 111   6   2   3   4   5   6]
[  6   2   3   4   5   6   1  11 111]


In [419]:
c=np.array([[6,2,3],[4,5,6]])
print(c)
print()

print(c.reshape(6))
print()

print(c.reshape(1,6))
print()

print(c.reshape(6,1))
print()

# print(c.reshape((1,2)))#cannot reshape array of size 6 into shape (1,2)
# print(c.reshape(7))#cannot reshape array of size 6 into shape (7)

print(c.reshape(3,2))
print()

print(c)#notes not change original nparray


[[6 2 3]
 [4 5 6]]

[6 2 3 4 5 6]

[[6 2 3 4 5 6]]

[[6]
 [2]
 [3]
 [4]
 [5]
 [6]]

[[6 2]
 [3 4]
 [5 6]]

[[6 2 3]
 [4 5 6]]


In [420]:
c=np.array([[6,2,3],[4,5,6]])
print(c)
print()

print(c.resize(6))
print(c)
print()

print(c.resize(1,6))
print(c)
print()

print(c.resize(6,1))
print(c)
print()

print(c.resize((1,2)))#notes deleted most values
print(c)
print()

print(c.resize(7))#
print(c)
print()

print(c.resize(3,2))
print(c)
print()

print(c)#notes original nparray form change all time.


[[6 2 3]
 [4 5 6]]

None
[6 2 3 4 5 6]

None
[[6 2 3 4 5 6]]

None
[[6]
 [2]
 [3]
 [4]
 [5]
 [6]]

None
[[6 2]]

None
[6 2 0 0 0 0 0]

None
[[6 2]
 [0 0]
 [0 0]]

[[6 2]
 [0 0]
 [0 0]]


In [421]:
a=np.array([23,24,25])
b=np.insert(a,1,5)# add 5 at index=1
print(a)
print(b)

[23 24 25]
[23  5 24 25]


In [422]:
print(b)
print(np.delete(b,1))
print(b)

[23  5 24 25]
[23 24 25]
[23  5 24 25]


In [423]:
c=np.array([[6,2,3],[4,5,6]])
print(c)
print()

print(c.T)
print()

print(c)
print()

[[6 2 3]
 [4 5 6]]

[[6 4]
 [2 5]
 [3 6]]

[[6 2 3]
 [4 5 6]]



In [424]:
#use nparray
# nparr=np.arange(1,16).reshape(4,4)# cannot reshape array of size 15 into shape (4,4)
# nparr=np.arange(1,16).resize(4,4)# return NONE
nparr=np.arange(1,17)
nparr.resize(4,4)
print(nparr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [425]:
print(nparr[3])
print(nparr[1,3])
print(nparr[1][3])
# print(nparr[4])#index 4 is out of bounds for axis 0 with size 4


[13 14 15 16]
8
8


In [426]:
nparr[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [427]:
nparr[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [428]:
nparr[:2] #all rows 0,1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [429]:
nparr[1:2] #all rows 1,2

array([[5, 6, 7, 8]])

In [430]:
nparr[:,2] #all rows but need 3 columns

array([ 3,  7, 11, 15])

In [431]:
nparr[:,0:2] #all rows but need 0,1 columns

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [432]:
# nparr[a>5] #boolean index did not match indexed array
print(nparr[nparr>5])
c=nparr.copy()
nparr[c>5]

[ 6  7  8  9 10 11 12 13 14 15 16]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Numpy array mathmatics

In [433]:
a=np.array([ 1,2 ,3])
b=np.array([[ 1,2 ,3],[4,5,6]])

print(a)
print()
print(b)


[1 2 3]

[[1 2 3]
 [4 5 6]]


In [447]:
print(a+3)
print(a*3)

print(np.add(a,3))
print(np.multiply(a,3))

[4 5 6]
[3 6 9]
[4 5 6]
[3 6 9]


In [434]:
print(a+b)

print(np.add(a,b))

[[2 4 6]
 [5 7 9]]
[[2 4 6]
 [5 7 9]]


In [435]:
print(b-a)

print(np.subtract(b,a))

[[0 0 0]
 [3 3 3]]
[[0 0 0]
 [3 3 3]]


In [436]:
print(a*b)

print(np.multiply(a,b))


[[ 1  4  9]
 [ 4 10 18]]
[[ 1  4  9]
 [ 4 10 18]]


In [437]:
print(b*a)

print(np.multiply(b,a))

[[ 1  4  9]
 [ 4 10 18]]
[[ 1  4  9]
 [ 4 10 18]]


## Numpy statical mathmatics

In [438]:

print(np.sqrt(b))
print(np.pow(b,2))
print(np.sin(b))
print(np.log(b))
print(np.exp(a))
print(np.e)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 1  4  9]
 [16 25 36]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[ 2.71828183  7.3890561  20.08553692]
2.718281828459045


In [439]:
nparr
print(nparr.sum)
print(nparr.sum())
print(np.sum(nparr))

print(nparr.min())
print(nparr.max())

print(nparr.mean())
print(np.mean(nparr))


print(nparr.std())#importnt
print(np.std(nparr))#importnt


# print(nparr.median()) not exists in math numpy only
print(np.median(nparr))





<built-in method sum of numpy.ndarray object at 0x00000239979CB8D0>
136
136
1
16
8.5
8.5
4.6097722286464435
4.6097722286464435
8.5


In [454]:
from numpy import *
a=poly1d([1,4,4])
print(a)


stay np.matrix only it is easy but need to focus

#np.dot(mat,mat)
#np.linalg.det(mat)
#np.linalg.matrix_rank(mat)
#arr.ravel()